# Generated by Django 4.0.3 on 2022-03-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCompany',
            fields=[
                ('fli_id', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
    ]
