# Generated by Django 4.0.3 on 2022-04-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_flightcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('fli_num', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('dep_hours', models.DateTimeField()),
                ('arriv_air', models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='arriv_airport', to='home.airport')),
                ('dep_air', models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='dept_airport', to='home.airport')),
            ],
        ),
    ]
