# Generated by Django 4.0.3 on 2022-04-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('seat_class', models.CharField(max_length=10)),
                ('pass_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('order_number', models.IntegerField(default=345, primary_key=True, serialize=False)),
                ('fli_company', models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='home.flightcompany')),
                ('fli_num', models.ForeignKey(default=1002, on_delete=django.db.models.deletion.CASCADE, to='home.flight')),
            ],
        ),
    ]
