# Generated by Django 4.0.3 on 2022-04-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('pro_type', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('air_id', models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='home.airport')),
            ],
        ),
    ]
