# Generated by Django 4.0.3 on 2022-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(default=400, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
