# Generated by Django 4.0.3 on 2022-04-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='type',
            new_name='ty',
        ),
    ]
