# Generated by Django 4.0.3 on 2022-04-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_type_supplier_ty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='ty',
            new_name='type',
        ),
    ]
