# Generated by Django 4.0.3 on 2022-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_ty_supplier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAgent',
            fields=[
                ('id', models.IntegerField(default=400, primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=50)),
                ('ag_name', models.CharField(max_length=50)),
            ],
        ),
    ]
